### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by dishamodi0910**
Added user and admin menu different.

### CODE REVIEW

**Review by yrncollo — COMMENTED** [review]
Thanks for your contribution...

**Comment by yrncollo** [comment]
Why have you commented out 313 lines of code?

**Comment by dishamodi0910** [comment]
The original yrncollo banking management system and the new system had different console friendly displays. So, just tried to maintain it here itself so there is no need to revert to the original code if the new one doesn't look formal.
I just attempted the original console display of yrncollo management system is in use as it seemed more console friendly.

Reagrds,
Disha Modi
Thank you.

**Comment by yrncollo** [comment]
> The original yrncollo banking management system and the new system had different console friendly displays. So, just tried to maintain it here itself so there is no need to revert to the original code if the new one doesn't look formal. I just attempted the original console display of yrncollo management system is in use as it seemed more console friendly.
> 
> Reagrds, Disha Modi Thank you.

Aaah smooth I now get it... So you were proposing we shift... Right?

**Comment by dishamodi0910** [comment]
Yeahhh!

**Comment by dishamodi0910** [comment]
Hey @yrncollo, should we start working on other systems as well simultaneously or we should first finish one, and then only we should move to another?

**Review by yrncollo — APPROVED** [review]

**Pull request merged**
