### PR TITLE
Code With Basic Banking System

### PR DESCRIPTION
**Pull request by kunalshah017**
Code contains features like
1.Creating a account
2.Setting and reseting pin for the account
3.Money adding and withdrawing from account

### CODE REVIEW

**Review by yrncollo — APPROVED** [review]
Well this is great for contributing to this project....

**Comment by kunalshah017** [comment]
Thank you for merging my code,
Will surely look into adding more features into it and completing the
project

**Comment by yrncollo** [comment]
Sure sure... so what I need you do is transfer the code to /src directory....

**Comment by kunalshah017** [comment]
> Sure sure... so what I need you do is transfer the code to /src directory....

Done :+1:  #22

**Pull request merged**
