### PR TITLE
Create sourceCode.cpp

### PR DESCRIPTION
**Pull request by Ayushagarwall007**
PASSWORD:  Pass@123

Payroll Management System is a Software that that is used to manage all your employee's financial records in a simple and automated fashion.

This payroll management system manages employee's salaries, deductions, other conveyance, net pay, bonuses and generation of pay-slips, etc.

### CODE REVIEW

**Comment by yrncollo** [comment]
Why have you closed the PR?

**Comment by Ayushagarwall007** [comment]
Actually someone has accessed my github and did it

**Comment by Ayushagarwall007** [comment]
Just checking it

**Comment by yrncollo** [comment]
> Just checking it

Sure

**Pull request closed without merging**
